#az login
#az account set --subscription "c1612ae2-5f15-487e-b926-fecaf634a54c"
location        = "westeurope"
rg              = "mgmt-rg"
vnet            = "mgmt-vnet"
subnet          = "mgmt-subnet"
rancherpublicip = "linux-ip"
ranchernsg      = "linux-nsg"
ranchernic      = "linux-nic"
ranchervmname   = "linux-vm"